{{- if and .Values.metrics.enabled .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "vm-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vm-manager.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "vm-manager.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      {{- with .Values.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
{{- end }}
